<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "error404page"
 *
 * Auto generated by Extension Builder 2016-05-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Error 404 page',
	'description' => 'Custom error 404 pages made simple. Use TYPO3 pages for display error documents. Works for multi domain and multilingual installations.',
	'category' => 'fe',
	'author' => 'R3 H6',
	'author_email' => 'r3h6@outlook.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);